config/routes.rb
IntegrityAdapter::Application.routes.draw do
  resources :justifications

end

app/models/justification.rb
class Justification < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/justifications_controller.rb
class JustificationsController < ApplicationController
  before_action :set_justification, only: [:show, :edit, :update, :destroy]

  # GET /justifications
  # GET /justifications.json
  def index
    @justifications = Justification.all
  end

  # GET /justifications/1
  # GET /justifications/1.json
  def show
  end

  # GET /justifications/new
  def new
    @justification = Justification.new
  end

  # GET /justifications/1/edit
  def edit
  end

  # POST /justifications
  # POST /justifications.json
  def create
    @justification = Justification.new(justification_params)

    respond_to do |format|
      if @justification.save
        format.html { redirect_to @justification, notice: 'Justification was successfully created.' }
        format.json { render action: 'show', status: :created, location: @justification }
      else
        format.html { render action: 'new' }
        format.json { render json: @justification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /justifications/1
  # PATCH/PUT /justifications/1.json
  def update
    respond_to do |format|
      if @justification.update(justification_params)
        format.html { redirect_to @justification, notice: 'Justification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @justification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /justifications/1
  # DELETE /justifications/1.json
  def destroy
    @justification.destroy
    respond_to do |format|
      format.html { redirect_to justifications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_justification
      @justification = Justification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def justification_params
      params.require(:justification).permit(:justId, :repo, :branch, :approved)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/justifications_helper.rb
module JustificationsHelper
end

app/views/justifications/_form.html.erb
<%= form_for(@justification) do |f| %>
  <% if @justification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@justification.errors.count, "error") %> prohibited this justification from being saved:</h2>

      <ul>
      <% @justification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :justId %><br>
    <%= f.number_field :justId %>
  </div>
  <div class="field">
    <%= f.label :repo %><br>
    <%= f.text_field :repo %>
  </div>
  <div class="field">
    <%= f.label :branch %><br>
    <%= f.text_field :branch %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/justifications/edit.html.erb
<h1>Editing justification</h1>

<%= render 'form' %>

<%= link_to 'Show', @justification %> |
<%= link_to 'Back', justifications_path %>

app/views/justifications/index.html.erb
<h1>Listing justifications</h1>

<table>
  <thead>
    <tr>
      <th>Justid</th>
      <th>Repo</th>
      <th>Branch</th>
      <th>Approved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @justifications.each do |justification| %>
      <tr>
        <td><%= justification.justId %></td>
        <td><%= justification.repo %></td>
        <td><%= justification.branch %></td>
        <td><%= justification.approved %></td>
        <td><%= link_to 'Show', justification %></td>
        <td><%= link_to 'Edit', edit_justification_path(justification) %></td>
        <td><%= link_to 'Destroy', justification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Justification', new_justification_path %>

app/views/justifications/new.html.erb
<h1>New justification</h1>

<%= render 'form' %>

<%= link_to 'Back', justifications_path %>

app/views/justifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Justid:</strong>
  <%= @justification.justId %>
</p>

<p>
  <strong>Repo:</strong>
  <%= @justification.repo %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @justification.branch %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @justification.approved %>
</p>

<%= link_to 'Edit', edit_justification_path(@justification) %> |
<%= link_to 'Back', justifications_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntegrityAdapter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>